CREATE DATABASE Q2DB;
USE Q2DB;



CREATE TABLE ENROLLMENT 
(SID INTEGER NOT NULL, 
ClassName VARCHAR(50) NOT NULL, 
Grade VARCHAR(2) NOT NULL, 
PRIMARY KEY (SID, ClassName));

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (123, 'Processing', 'A');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (123, 'Python', 'B');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (123, 'Scratch', 'B');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (662, 'Java', 'B');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (662, 'Python', 'A');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (662, 'JavaScript', 'A');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (662, 'Scratch', 'B');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (345, 'Scratch', 'A');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (345, 'JavaScript', 'B');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (345, 'Python', 'A');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (555, 'Python', 'B');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (555, 'JavaScript', 'B');

INSERT INTO ENROLLMENT(SID, ClassName, Grade) VALUES (213, 'JavaScript', 'A');

SELECT *  
FROM ENROLLMENT;

SELECT ClassName, COUNT(ClassName) AS Total 
FROM ENROLLMENT 
GROUP BY ClassName 
ORDER BY Total desc;

