CREATE DATABASE Q3DB;
USE Q3DB;


CREATE TABLE STU_PROJECT 
(PID VARCHAR(50) NOT NULL,  
Step INTEGER NOT NULL,  
Status VARCHAR(2) NOT NULL,  
PRIMARY KEY (PID, Step), 
CHECK (Status = 'C' OR Status = 'W'));

INSERT INTO STU_PROJECT  VALUES ('P100', 0, 'C');

INSERT INTO STU_PROJECT  VALUES ('P100', 1, 'W');

INSERT INTO STU_PROJECT  VALUES ('P100', 2, 'W');

INSERT INTO STU_PROJECT  VALUES ('P201', 0, 'C');

INSERT INTO STU_PROJECT  VALUES ('P201', 1, 'C');

INSERT INTO STU_PROJECT  VALUES ('P333', 0, 'W');

INSERT INTO STU_PROJECT  VALUES ('P333', 1, 'W');

INSERT INTO STU_PROJECT  VALUES ('P333', 2, 'W');

INSERT INTO STU_PROJECT  VALUES ('P333', 3, 'W');

SELECT *   
FROM STU_PROJECT;

SELECT A.PID  
FROM STU_PROJECT A, STU_PROJECT B 
WHERE A.PID = B.PID AND A.Step = 0 AND A.Status = 'C' AND B.Step = 1 AND B.Status = 'W';

